name: build-frontend
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Create docker image
        working-directory: ./frontend
        run: DOCKER_BUILDKIT=1 docker build --output type=tar,dest=frontend_webserver_docker_image.tar .
      - uses: actions/upload-artifact@v3
        with:
          name: frontend_webserver_docker_image.tar
          path: frontend/frontend_webserver_docker_image.tar
