name: build-frontend
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Create docker image
        working-directory: ./frontend
        run: docker build .
